INSERT INTO public_vaba.category (id, name) VALUES (DEFAULT, 'sport');
INSERT INTO public_vaba.category (id, name) VALUES (DEFAULT, 'muusika');
INSERT INTO public_vaba.category (id, name) VALUES (DEFAULT, 'loodus');
INSERT INTO public_vaba.category (id, name) VALUES (DEFAULT, 'muu');

INSERT INTO public_vaba.language (id, name) VALUES (DEFAULT, 'eesti');
INSERT INTO public_vaba.language (id, name) VALUES (DEFAULT, 'vene');
INSERT INTO public_vaba.language (id, name) VALUES (DEFAULT, 'inglise');

INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Valgamaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Tartumaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Harjumaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Saaremaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Hiiumaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Võrumaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Pärnumaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Põlvamaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Läänemaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Lääne-Virumaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Ida-Virumaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Jõgevamaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Raplamaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Järvamaa');
INSERT INTO public_vaba.county (id, name) VALUES (DEFAULT, 'Viljandimaa');

INSERT INTO public_vaba.role (id, name) VALUES (DEFAULT, 'admin');
INSERT INTO public_vaba.role (id, name) VALUES (DEFAULT, 'kasutaja');

INSERT INTO public_vaba.contact (id, first_name, last_name, sex, email) VALUES (DEFAULT, 'Mart', 'Tamm', 'M', 'asdas@gmail.com');
INSERT INTO public_vaba.contact (id, first_name, last_name, sex, email) VALUES (DEFAULT, 'Gulba', 'Hammas', 'N', 'abudhabi@hot.ru');
INSERT INTO public_vaba.contact (id, first_name, last_name, sex, email) VALUES (DEFAULT, 'Anton', 'Leib', 'M', 'eesti@hot.ee');
INSERT INTO public_vaba.contact (id, first_name, last_name, sex, email) VALUES (DEFAULT, 'Maie', 'Kalames', 'N', 'ruigab@gmail.com');
INSERT INTO public_vaba.contact (id, first_name, last_name, sex, email) VALUES (DEFAULT, 'Mati', 'Kask', 'M', 'matikask15@gmail.com');
INSERT INTO public_vaba.contact (id, first_name, last_name, sex, email) VALUES (DEFAULT, 'Tiina', 'Alke', 'N', 'tiina.alke@hotmail.com');
INSERT INTO public_vaba.contact (id, first_name, last_name, sex, email) VALUES (DEFAULT, 'Piia', 'Loon', 'N', 'piima543@hot.ee');
INSERT INTO public_vaba.contact (id, first_name, last_name, sex, email) VALUES (DEFAULT, 'Kaarel', 'Veela', 'M', 'kaarel.ve@gmail.com');
INSERT INTO public_vaba.contact (id, first_name, last_name, sex, email) VALUES (DEFAULT, 'Olivier', 'Rouiller', 'M', 'perfect@gmail.com');

INSERT INTO public_vaba."user" (id, username, password, status, contact_id, role_id) VALUES (DEFAULT, 'admin', '123', DEFAULT, null, 1);
INSERT INTO public_vaba."user" (id, username, password, status, contact_id, role_id) VALUES (DEFAULT, 'siim', 'piim', DEFAULT, 1, 2);
INSERT INTO public_vaba."user" (id, username, password, status, contact_id, role_id) VALUES (DEFAULT, 'qwe', 'asd', false, 9, 2);
INSERT INTO public_vaba."user" (id, username, password, status, contact_id, role_id) VALUES (DEFAULT, 'maamees', '8989', DEFAULT, 2, 2);
INSERT INTO public_vaba."user" (id, username, password, status, contact_id, role_id) VALUES (DEFAULT, 'antonl', 'anton123', true, 3, DEFAULT);
INSERT INTO public_vaba."user" (id, username, password, status, contact_id, role_id) VALUES (DEFAULT, 'maiekal', 'maie123', true, 4, DEFAULT);
INSERT INTO public_vaba."user" (id, username, password, status, contact_id, role_id) VALUES (DEFAULT, 'tiinaa', 'tiina123', true, 6, DEFAULT);
INSERT INTO public_vaba."user" (id, username, password, status, contact_id, role_id) VALUES (DEFAULT, 'piial', 'piia123', true, 7, DEFAULT);
INSERT INTO public_vaba."user" (id, username, password, status, contact_id, role_id) VALUES (DEFAULT, 'kaarelv', 'kaarel123', true, 8, DEFAULT);
INSERT INTO public_vaba."user" (id, username, password, status, contact_id, role_id) VALUES (DEFAULT, 'matik', 'mati123', true, 5, DEFAULT);


INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Pöösas 4-6-8', null, null, 1);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Klakh 9', null, null, 2);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Susal 998', null, null, 5);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Eras 998', null, null, 1);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Velasd 55', null, null, 11);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Põllu 5', null, null, 3);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Tamme 6', null, null, 4);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Paju tee 7', null, null, 4);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Kuuskiku 14', null, null, 5);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Virmalise 102', null, null, 6);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Telliskivi 156', null, null, 7);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Vabaduse pst 90', null, null, 8);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Aia tee 3', null, null, 9);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Valla tn 54', null, null, 10);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Muuli 4', null, null, 11);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Kaera 1', null, null, 12);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Nisu 45', null, null, 12);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Aeru 91', null, null, 13);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Oksa 11', null, null, 14);
INSERT INTO public_vaba.location (id, address, longtitude, latitude, county_id) VALUES (DEFAULT, 'Lille 5', null, null, 15);

INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Murutraktor', '2022-09-16', '2022-09-17', 10, 1, 1, null, 1, 'e', 2);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Huumor', '2021-09-29', '2021-09-30', 100, 2, 2, null, 2, 'e', 4);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Koolja', '2022-10-12', '2022-10-21', 11, 2, 1, null, 3, 'v', 2);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Neoplan', '2022-10-20', '2022-10-29', 65, 3, 1, null, 2, 'v', 4);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Lada', '2022-10-18', '2022-10-21', 23, 1, 1, null, 1, 'v', 2);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Volkar', '2022-11-18', '2022-11-21', 41, 2, 2, null, 2, 'c', 4);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Audi', '2022-10-03', '2022-10-05',68, 1, 2, null, 1, 'v', 2);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Part', '2022-10-10', '2022-10-21', 78, 3, 3, null, 3, 'c', 4);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Proov', '2023-09-02', '2023-09-30', 3, 4, 1, null, 2, DEFAULT, 3);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Kallas', '2022-11-25', '2022-12-06', 71, 1, 1, null, 2, 'c', 3);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Rullik', '2022-12-22', '2022-12-26', 500, 2, 1, null, 3, 'c', 3);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'IronMan', '2022-09-12', '2022-09-14', 55, 1, 3, 'https://www.ironman.com/', 6, 'e', 5);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Kalamaja päevad', '2022-08-09', '2022-08-11', 15, 4, 1, null, 8, 'e', 6);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Hiiumaa kodukohvikud', '2022-09-01', '2022-09-01', 10, 4, 1, null, 6, 'e', 7);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Unistuste päev', '2022-08-07', '2022-08-07', 5, 4, 2, null, 9, 'e', 8);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Pesaleidja', '2022-11-12', '2022-11-16', 20, 4, 1, 'https://www.pesaleidja.ee/', 10, 'e', 9);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Pannkoogipühapäev lastele', '2022-10-01', '2022-10-01', 7, 4, 1, null, 12, 'v', 10);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Koristustalgud', '2022-10-14', '2022-10-15', 150, 3, 1, null, 11, 'v', 5);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Õllesummer', '2022-11-01', '2022-11-05', 45, 2, 1, null, 7, 'v', 6);
INSERT INTO public_vaba.event (id, event_name, start_date, end_date, volunteers_required, category_id, language_id, link, location_id, status, user_id) VALUES (DEFAULT, 'Vabaõhuüritus', '2022-09-25', '2022-09-27', 32, 2, 3, null, 19, 'c', 7);


INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Tere', DEFAULT, 1);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Mängima', DEFAULT, 1);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Marssima', DEFAULT, 2);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Koolja', DEFAULT, 3);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Seda', DEFAULT, 4);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Toda', DEFAULT, 5);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Wer', DEFAULT, 5);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Man', DEFAULT, 3);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'WH', DEFAULT, 3);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Poolik', DEFAULT, 2);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Joogipudelite jagamine', true, 12);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Medalite üle andmine', true, 12);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Diplomite kirjutamine', true, 12);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Kassas töötamine', true, 13);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Siltide seadmine', true, 13);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Saiakeste valmistaine', true, 14);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Laudade teenindamine', true, 14);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Külaliste juhendamine', true, 14);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Projektijuhi abistamine', true, 15);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Pildistamine', true, 15);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Patside punumine', true, 15);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Näomaalingute tegemine lastele', true, 15);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Kassipoegadega mängimine', true, 16);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Koertega jalutamine', true, 16);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Loomade kammimine', true, 16);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Koerakuutide ehitamine', true, 16);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Pannkookide küpsetamine', true, 17);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Laudade koristamine', true, 17);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Mängujuht lastele', true, 17);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Bussipeatuste pesemine', true, 17);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Lehtede riisumine', true, 17);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Prügikottide vedamine (vajab juhtimisõigust)', true, 17);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Piletimüük kassas', true, 18);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Lava üles seadmine', true, 19);
INSERT INTO public_vaba.task (id, name, status, event_id) VALUES (DEFAULT, 'Flaierite jagamine', true, 20);

INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Paranda', DEFAULT, 2);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Tuulika', DEFAULT, 1);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Lammuta', DEFAULT, 2);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Emma', DEFAULT, 3);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Gabi', DEFAULT, 3);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Mabi', DEFAULT, 4);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Savi', DEFAULT, 5);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Liiv', DEFAULT, 3);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Vajab valmisolekut pikaks päevaks (12h)', true, 12);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Pakume toitlustust', true, 12);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Riietuda vastavalt ilmale', true, 12);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Päev on täis rõõmsaid inimesi', true, 13);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Võimalus päev veeta vabas õhus', true, 13);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Pakume toitlustust', true, 13);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Vajab valmisolekut suhtlemiseks erinevates keeltes (eesti, inglise, vene)', true, 13);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Vajadusel korraldame transporti kohale saamiseks', true, 14);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Pakume maitsvaid toiduelamusi kõigile vabatahtlikele', true, 14);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Võimalus päev veeta vabas õhus', true, 14);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Sobiva koostöö korral võimalus jätkamiseks', true, 15);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Vajab valmisolekut kokkupuuteks eriliste lastega', true, 15);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Ajakava võib muutuda', true, 15);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Soovi korral tutvustame hoiukodu pakkumise võimalusi', true, 16);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Oodatud on ka kuudi ehistuseks materjalide pakkumine', true, 16);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Sobivuse korral võimalus vabatahtlikuna koostöö jätkamiseks', true, 16);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Vajab valmisolekut lastega suhtlemiseks', true, 17);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Kõik vahendid meie poolt', true, 17);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Pakume kogu päeva jooksul ka toitlustust', true, 17);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Võimalusel kaasa võtta vahendeid (rehad jmt)', true, 18);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Riietuda vastavalt ilmale', true, 18);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Vajab töövahendeid mugavaks töötamiskes (soovitame kindad, maskid, sobivad jalanõud jmt)', true, 18);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Sobib ka perekondlikuks ettevõtmiseks', true, 18);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Toitlustus tuleb ise organiseerida', true, 18);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Töö sobib meesterahvale, töö on füüsiline', true, 19);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Tegevus 1-2h', true, 20);
INSERT INTO public_vaba.additional_info (id, name, status, event_id) VALUES (DEFAULT, 'Peale tegevust võimalus üritusele jääda', true, 20);

INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 10, null, 2, DEFAULT, 2);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 15, null, 2, DEFAULT, 10);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 22, null, 3, DEFAULT, 6);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 23, null, 9, true, 12);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 8, null, 4, true, 13);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 3, null, 5, true, 14);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 2, null, 6, true, 15);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 17, null, 8, true, 16);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 6, null, 5, true, 17);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 13, null, 9, true, 18);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 24, null, 8, true, 19);
INSERT INTO public_vaba.volunteer (id, volunteers_size, info, user_id, status, event_id) VALUES (DEFAULT, 13, null, 5, true, 20);

INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2021-09-29', 100, DEFAULT, true, 2);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2021-09-30', 100, DEFAULT, true, 2);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-18', 23, 0, true, 5);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-19', 23, 0, true, 5);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-20', 23, 0, true, 5);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-21', 23, 0, true, 5);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-09-16', 10, 0, true, 1);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-09-17', 10, 0, true, 1);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-12', 11, 0, true, 3);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-13', 11, 0, true, 3);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-14', 11, 0, true, 3);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-15', 11, 0, true, 3);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-16', 11, 0, true, 3);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-17', 11, 0, true, 3);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-18', 11, 0, true, 3);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-19', 11, 0, true, 3);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-20', 11, 0, true, 3);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-21', 11, 0, true, 3);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-20', 65, 0, true, 4);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-21', 65, 0, true, 4);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-22', 65, 0, true, 4);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-23', 65, 0, true, 4);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-24', 65, 0, true, 4);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-25', 65, 0, true, 4);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-26', 65, 0, true, 4);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-27', 65, 0, true, 4);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-28', 65, 0, true, 4);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-29', 65, 0, true, 4);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-18', 23, 0, true, 5);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-19', 23, 0, true, 5);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-20', 23, 0, true, 5);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-21', 23, 0, true, 5);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-18', 41, 0, true, 6);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-19', 41, 0, true, 6);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-20', 41, 0, true, 6);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-21', 41, 0, true, 6);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-03', 68, 0, true, 7);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-04', 68, 0, true, 7);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-05', 68, 0, true, 7);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-10', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-11', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-12', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-13', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-14', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-15', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-16', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-17', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-18', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-19', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-20', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-21', 78, 0, true, 8);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-02', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-03', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-04', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-05', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-06', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-07', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-08', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-09', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-10', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-11', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-12', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-13', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-14', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-15', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-16', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-17', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-18', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-19', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-20', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-21', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-22', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-23', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-24', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-25', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-26', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-27', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-28', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-29', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2023-09-30', 3, 0, true, 9);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-25', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-26', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-27', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-28', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-29', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-30', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-01', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-02', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-03', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-04', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-05', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-06', 71, 0, true, 10);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-22', 500, 0, true, 11);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-23', 500, 0, true, 11);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-24', 500, 0, true, 11);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-25', 500, 0, true, 11);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-12-26', 500, 0, true, 11);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-09-12', 55, 0, true, 12);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-09-13', 55, 0, true, 12);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-09-14', 55, 0, true, 12);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-08-09', 15, 0, true, 13);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-08-10', 15, 0, true, 13);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-08-11', 15, 0, true, 13);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-09-01', 10, 0, true, 14);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-08-07', 5, 0, true, 15);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-07-12', 20, 0, true, 16);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-07-13', 20, 0, true, 16);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-07-14', 20, 0, true, 16);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-07-15', 20, 0, true, 16);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-07-16', 20, 0, true, 16);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-01', 7, 0, true, 17);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-14', 150, 0, true, 18);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-10-15', 150, 0, true, 18);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-01', 45, 0, true, 19);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-02', 45, 0, true, 19);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-03', 45, 0, true, 19);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-04', 45, 0, true, 19);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-11-05', 45, 0, true, 19);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-09-25', 32, 0, true, 20);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-09-26', 32, 0, true, 20);
INSERT INTO public_vaba.event_date (id, date, volunteers_required, volunteers_assigned, is_active, event_id) VALUES (DEFAULT, '2022-09-27', 32, 0, true, 20);

INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 2, 1);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 98, 4);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 34, 3);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 101, 5);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 36, 6);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 105, 7);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 106, 8);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 11, 9);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 113, 10);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 114, 11);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 119, 12);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 1, 1);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 81, 2);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 34, 3);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 99, 4);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 102, 5);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 35, 6);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 105, 7);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 107, 8);
INSERT INTO public_vaba.volunteer_event_date (id, event_date_id, volunteer_id) VALUES (DEFAULT, 99, 4);

INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 12, 20);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 11, 19);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 10, 18);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 9, 27);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 9, 28);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 9, 29);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 9, 30);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 9, 31);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 9, 32);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 8, 23);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 8, 24);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 8, 25);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 8, 26);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 7, 19);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 7, 20);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 7, 21);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 7, 22);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 6, 14);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 6, 14);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 6, 14);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 5, 13);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 4, 12);
INSERT INTO public_vaba.volunteer_task (id, volunteer_id, task_id) VALUES (DEFAULT, 4, 12)

-- SET search_path TO public;